package com.task.Entity;

import java.util.Date;

import com.task.ENUM.Role;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity // JPA annotation – maps this class to a database table
@Table(name = "user_auth")
@Data // Generates getters, setters, toString, equals & hashCode
@NoArgsConstructor // No-argument constructor
@AllArgsConstructor // All-argument constructor
@Builder
@Getter
@Setter
public class UserAuth {

	// Encapsulation 
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // autogenerated ids
    private Long id;
    
    @Column(nullable=false) // can't be empty 
    private String userName;
    
    @Column(nullable=false,unique=true)  // should be unique
    private String userOfficialEmail;
    
    @Column(nullable=false)
    private String password;

    @Enumerated(EnumType.STRING)
      private Role role;
    

	private String resetToken;
    private Date resetTokenExpiry; // will fetch from system timings // LocalDate takes region wise
    
//    // Constructor 
//      public UserAuth() {} // NoArgsConstructor - build automatically but variables are not automatically assigned 
//      public UserAuth(Long id,String userName,String userEmail,String password, Role role) {
//    	  this.id=id; // this keyword is used for instance variable and constructor for calling variables 
//    	  this.userName=userName;
//    	  this.userEmail=userEmail;
//    	  this.password=password;
//    	  this.role=role;
//      }

    // Method Creation 
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserOfficialEmail() {
		return userOfficialEmail;
	}

	public void setUserOfficialEmail(String userEmail) {
		this.userOfficialEmail = userEmail;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}
	
    public String getResetToken() {
		return resetToken;
	}

	public void setResetToken(String resetToken) {
		this.resetToken = resetToken;
	}

	public Date getResetTokenExpiry() {
		return resetTokenExpiry;
	}

	public void setResetTokenExpiry(Date resetTokenExpiry) {
		this.resetTokenExpiry = resetTokenExpiry;
	}
}
